### ISSUE TITLE
COBS encode from Postcard

### ISSUE THREAD

**Issue by MathiasKoch** [BlackbirdHQ/defmt-persist#5]
Currently the COBS encoding decoding is done "manually", but should be possible to get working as a `postcard` flavor

**Comment by jamesmunns** [comment]
FYI postcard already has a COBS flavor! for example:

https://docs.rs/postcard/0.5.1/postcard/fn.to_slice_cobs.html

let me know if you need any changes to make it work!

**Comment by MathiasKoch** [comment]
Yeah, i tried that but couldn't quite make it work.. I am fairly sure it was my mistake though, so this issue was mostly a reminder to look at it again at some point.. 

Also I think i might need some framing support in `defmt` first anyways (#3 )
